export const countries = [
    { countryCode: 'US', label: 'United States' },
    { countryCode: 'CA', label: 'Canada' },
    { countryCode: 'GB', label: 'United Kingdom' },
    { countryCode: 'AU', label: 'Australia' },
    { countryCode: 'DE', label: 'Germany' },
    { countryCode: 'FR', label: 'France' },
    { countryCode: 'IT', label: 'Italy' },
    { countryCode: 'ES', label: 'Spain' },
    { countryCode: 'BG', label: 'Bulgaria' },
    { countryCode: 'GR', label: 'Greece' },
    { countryCode: 'TR', label: 'Turkey' },
    { countryCode: 'RU', label: 'Russia' },
    { countryCode: 'CN', label: 'China' },
    { countryCode: 'JP', label: 'Japan' },
    { countryCode: 'IN', label: 'India' },
    { countryCode: 'BR', label: 'Brazil' },
    { countryCode: 'MX', label: 'Mexico' },
    { countryCode: 'AR', label: 'Argentina' },
    { countryCode: 'ZA', label: 'South Africa' },
    { countryCode: 'NG', label: 'Nigeria' },
    { countryCode: 'EG', label: 'Egypt' },
    { countryCode: 'SA', label: 'Saudi Arabia' },
    { countryCode: 'AE', label: 'United Arab Emirates' },
    { countryCode: 'SE', label: 'Sweden' },
    { countryCode: 'NO', label: 'Norway' },
    { countryCode: 'FI', label: 'Finland' },
    { countryCode: 'DK', label: 'Denmark' },
    { countryCode: 'NL', label: 'Netherlands' },
    { countryCode: 'BE', label: 'Belgium' },
    { countryCode: 'CH', label: 'Switzerland' },
    { countryCode: 'AT', label: 'Austria' },
    { countryCode: 'PT', label: 'Portugal' },
    { countryCode: 'IE', label: 'Ireland' },
    { countryCode: 'PL', label: 'Poland' },
    { countryCode: 'CZ', label: 'Czech Republic' },
    { countryCode: 'HU', label: 'Hungary' },
    { countryCode: 'RO', label: 'Romania' },
    { countryCode: 'RS', label: 'Serbia' },
    { countryCode: 'HR', label: 'Croatia' },
    { countryCode: 'SI', label: 'Slovenia' },
    { countryCode: 'SK', label: 'Slovakia' },
    { countryCode: 'UA', label: 'Ukraine' },
    { countryCode: 'BY', label: 'Belarus' },
    { countryCode: 'LT', label: 'Lithuania' },
    { countryCode: 'LV', label: 'Latvia' },
    { countryCode: 'EE', label: 'Estonia' },
    { countryCode: 'IS', label: 'Iceland' },
    { countryCode: 'AL', label: 'Albania' },
    { countryCode: 'MK', label: 'North Macedonia' },
    { countryCode: 'ME', label: 'Montenegro' },
    { countryCode: 'BA', label: 'Bosnia and Herzegovina' },
    { countryCode: 'MD', label: 'Moldova' },
    { countryCode: 'GE', label: 'Georgia' },
    { countryCode: 'AM', label: 'Armenia' },
    { countryCode: 'AZ', label: 'Azerbaijan' },
    { countryCode: 'KZ', label: 'Kazakhstan' },
    { countryCode: 'UZ', label: 'Uzbekistan' },
    { countryCode: 'TH', label: 'Thailand' },
    { countryCode: 'VN', label: 'Vietnam' },
    { countryCode: 'ID', label: 'Indonesia' },
    { countryCode: 'MY', label: 'Malaysia' },
    { countryCode: 'PH', label: 'Philippines' },
    { countryCode: 'SG', label: 'Singapore' },
    { countryCode: 'KR', label: 'South Korea' },
    { countryCode: 'KP', label: 'North Korea' },
    { countryCode: 'HK', label: 'Hong Kong' },
    { countryCode: 'TW', label: 'Taiwan' },
    { countryCode: 'MO', label: 'Macau' },
    { countryCode: 'BD', label: 'Bangladesh' },
    { countryCode: 'PK', label: 'Pakistan' },
    { countryCode: 'LK', label: 'Sri Lanka' },
    { countryCode: 'NP', label: 'Nepal' },
    { countryCode: 'IR', label: 'Iran' },
    { countryCode: 'IQ', label: 'Iraq' },
    { countryCode: 'SY', label: 'Syria' },
    { countryCode: 'LB', label: 'Lebanon' },
    { countryCode: 'JO', label: 'Jordan' },
    { countryCode: 'IL', label: 'Israel' },
    { countryCode: 'PS', label: 'Palestine' },
    { countryCode: 'KW', label: 'Kuwait' },
    { countryCode: 'QA', label: 'Qatar' },
    { countryCode: 'BH', label: 'Bahrain' },
    { countryCode: 'OM', label: 'Oman' },
    { countryCode: 'YE', label: 'Yemen' },
    { countryCode: 'AF', label: 'Afghanistan' },
    { countryCode: 'LK', label: 'Sri Lanka' },
    { countryCode: 'MV', label: 'Maldives' },
    { countryCode: 'BT', label: 'Bhutan' },
    { countryCode: 'MN', label: 'Mongolia' },
    { countryCode: 'LA', label: 'Laos' },
    { countryCode: 'KH', label: 'Cambodia' },
    { countryCode: 'MM', label: 'Myanmar' },
    { countryCode: 'BN', label: 'Brunei' },
    { countryCode: 'TL', label: 'Timor-Leste' },
    { countryCode: 'FJ', label: 'Fiji' },
    { countryCode: 'SB', label: 'Solomon Islands' },
    { countryCode: 'VU', label: 'Vanuatu' },
    { countryCode: 'PG', label: 'Papua New Guinea' },
    { countryCode: 'WS', label: 'Samoa' },
    { countryCode: 'KI', label: 'Kiribati' },
    { countryCode: 'TO', label: 'Tonga' },
    { countryCode: 'FM', label: 'Micronesia' },
    { countryCode: 'MH', label: 'Marshall Islands' },
    { countryCode: 'PW', label: 'Palau' },
    { countryCode: 'NR', label: 'Nauru' },
    { countryCode: 'TV', label: 'Tuvalu' },
    { countryCode: 'NZ', label: 'New Zealand' },
    { countryCode: 'CL', label: 'Chile' },
    { countryCode: 'PE', label: 'Peru' },
    { countryCode: 'CO', label: 'Colombia' },
    { countryCode: 'VE', label: 'Venezuela' },
    { countryCode: 'EC', label: 'Ecuador' },
    { countryCode: 'BO', label: 'Bolivia' },
    { countryCode: 'PY', label: 'Paraguay' },
    { countryCode: 'UY', label: 'Uruguay' },
    { countryCode: 'CR', label: 'Costa Rica' },
    { countryCode: 'PA', label: 'Panama' },
    { countryCode: 'NI', label: 'Nicaragua' },
    { countryCode: 'HN', label: 'Honduras' },
    { countryCode: 'SV', label: 'El Salvador' },
    { countryCode: 'GT', label: 'Guatemala' },
    { countryCode: 'BZ', label: 'Belize' },
    { countryCode: 'CU', label: 'Cuba' },
    { countryCode: 'JM', label: 'Jamaica' },
    { countryCode: 'HT', label: 'Haiti' },
    { countryCode: 'DO', label: 'Dominican Republic' },
    { countryCode: 'PR', label: 'Puerto Rico' },
    { countryCode: 'BS', label: 'Bahamas' },
    { countryCode: 'BB', label: 'Barbados' },
    { countryCode: 'GD', label: 'Grenada' },
    { countryCode: 'LC', label: 'Saint Lucia' },
    { countryCode: 'VC', label: 'Saint Vincent and the Grenadines' },
    { countryCode: 'KN', label: 'Saint Kitts and Nevis' },
    { countryCode: 'DM', label: 'Dominica' },
    { countryCode: 'AG', label: 'Antigua and Barbuda' },
    { countryCode: 'TT', label: 'Trinidad and Tobago' },
    { countryCode: 'SR', label: 'Suriname' },
    { countryCode: 'GY', label: 'Guyana' },
    { countryCode: 'GF', label: 'French Guiana' },
    { countryCode: 'GL', label: 'Greenland' },
    { countryCode: 'BM', label: 'Bermuda' },
    { countryCode: 'KY', label: 'Cayman Islands' },
    { countryCode: 'TC', label: 'Turks and Caicos Islands' },
    { countryCode: 'VG', label: 'British Virgin Islands' },
    { countryCode: 'VI', label: 'U.S. Virgin Islands' },
    { countryCode: 'AI', label: 'Anguilla' },
    { countryCode: 'MS', label: 'Montserrat' },
    { countryCode: 'AW', label: 'Aruba' },
    { countryCode: 'CW', label: 'Curaçao' },
    { countryCode: 'SX', label: 'Sint Maarten' },
    { countryCode: 'BQ', label: 'Caribbean Netherlands' },
    { countryCode: 'MF', label: 'Saint Martin' },
    { countryCode: 'BL', label: 'Saint Barthélemy' },
    { countryCode: 'PM', label: 'Saint Pierre and Miquelon' },
    { countryCode: 'WF', label: 'Wallis and Futuna' },
    { countryCode: 'PF', label: 'French Polynesia' },
    { countryCode: 'NC', label: 'New Caledonia' },
    { countryCode: 'CK', label: 'Cook Islands' },
    { countryCode: 'NU', label: 'Niue' },
    { countryCode: 'TK', label: 'Tokelau' },
    { countryCode: 'FK', label: 'Falkland Islands' },
    { countryCode: 'GS', label: 'South Georgia and the South Sandwich Islands' },
    { countryCode: 'TF', label: 'French Southern Territories' },
    { countryCode: 'HM', label: 'Heard Island and McDonald Islands' },
    { countryCode: 'AQ', label: 'Antarctica' },
    { countryCode: 'SJ', label: 'Svalbard and Jan Mayen' },
    { countryCode: 'BV', label: 'Bouvet Island' },
    { countryCode: 'IO', label: 'British Indian Ocean Territory' },
    { countryCode: 'CX', label: 'Christmas Island' },
    { countryCode: 'CC', label: 'Cocos (Keeling) Islands' },
    { countryCode: 'NF', label: 'Norfolk Island' },
    { countryCode: 'UM', label: 'United States Minor Outlying Islands' },
    { countryCode: 'AS', label: 'American Samoa' },
    { countryCode: 'GU', label: 'Guam' },
    { countryCode: 'MP', label: 'Northern Mariana Islands' },
    { countryCode: 'PW', label: 'Palau' },
    { countryCode: 'UM', label: 'United States Minor Outlying Islands' },
    { countryCode: 'VI', label: 'U.S. Virgin Islands' }
  ];



export const getCountryFlag = (countryName) => {
  if (!countryName || countryName.toUpperCase() === 'UNKNOWN') return '🌎';

  return countries.find(country => country.countryCode == countryName).label || '🌎';
};