name: Server CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Jest tests
        working-directory: ./server
        run: npm test
        env:
          NODE_ENV: test
          ACCESS_TOKEN_SECRET: ${{ secrets.JWT_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GROQ_AI_API_KEY: ${{ secrets.GROQ_AI_API_KEY }}
          GROQ_AI_MODEL: ${{ secrets.GROQ_AI_MODEL }}
          GROQ_AI_GUEST_PROMPT: ${{ secrets.GROQ_AI_GUEST_PROMPT }}
          GROQ_AI_LOGGED_IN_PROMPT: ${{ secrets.GROQ_AI_LOGGED_IN_PROMPT }}
          ADDITIONAL_INFO: ${{ secrets.ADDITIONAL_INFO }}
          LOCAL_FRONTEND_URL: ${{ secrets.LOCAL_FRONTEND_URL }}
          PRODUCTION_FRONTEND_URL: ${{ secrets.PRODUCTION_FRONTEND_URL }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_SERVICE: ${{ secrets.SMTP_SERVICE }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}